PROGRAM_NAME="OSS"


SIMULATION_LABEL="Simulation"


## Status Labels
PROCESS_RUNNING_LABEL="Executando:"
PROCESS_READY_LABEL="Pronto:"
PROCECSS_BLOCKED_LABEL="Bloqueado:"
PROCESS_FINISHED_LABEL="Finalizado:"
PROCESS_AVAILABLE_LABEL="Processos"