PROGRAM_NAME="OSS"


SIMULATION_LABEL="Simulation"
PROCESSES_LABEL="Processes"


## Status Labels
PROCESS_RUNNING_LABEL="Executando:"
PROCESS_READY_LABEL="Pronto:"
PROCECSS_BLOCKED_LABEL="Bloqueado:"
PROCESS_FINISHED_LABEL="Finalizado:"
PROCESS_AVAILABLE_LABEL="Processos"


## CPU STATUS
RAM="Ram:"
SWAP="Swap:"
PAGINATION="Paginação:"